version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: playqueue-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-playqueue}
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - playqueue_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  playqueue_data: